name: CI
run-name: ${{ github.actor }} run CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        working-directory: ./home/runner/work/avt114-labs-team-1/avt114-labs-team-1/libhv-http
      - run: sudo apt-get update
      - run: sudo apt-get install g++ make cmake
      - run: cd /home/runner/work/avt114-labs-team-1/avt114-labs-team-1/libhv-http
      - run: pwd
      - run: ls -al     
      - run: mkdir -p build && cd build && cmake .. && make
      - run: pwd
      - run: cd ..
      - run: pwd