name: CI
run-name: ${{ github.actor }} run CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3    
      - run: sudo apt-get update
      - run: sudo apt-get install g++ make cmake wget libgtest-dev libtbb-dev
      - run: mkdir -p build && cd build && cmake .. && make

      - run: cd ..
      - run: sh create_debpkg.sh
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: ./http-server-client-dcsa.deb
      - run: cd ..
      - name: Start server
        run: ./build/http-server &
      - name: Unit test
        run: cd build && ctest
      - run: cd ..
      - name: Smoke test
        run: |
          if wget --timeout=5 --tries=1 --spider http://localhost:7777/; then
            echo "Smoke test passed"
          else
            echo "Smoke test failed"
            exit 1
          fi
      - name: Stop server
        run: pkill http-server
      - name: Log in to Docker Hub
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
          with:
              images: lsdpewl1/server
      - name: Build and push Docker image
          id: push
          uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
          with:
              context: .
              file: ./Dockerfile
              push: true
              tags: ${{ steps.meta.outputs.tags }}
              labels: ${{ steps.meta.outputs.labels }}

